# デバッグ用の設定
FROM openjdk:11

WORKDIR /app
COPY ./build/libs/knowledge-0.0.1-SNAPSHOT.jar /app

CMD ["java", "-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8082", "knowledge-0.0.1-SNAPSHOT.jar"]