apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/PROJECT_ID/IMAGE:TAG
  newName: gcr.io/my-demo-project-20210227/knowledge
  newTag: c3346aae991f27b15bc2cbe212a6fbe150f94475
- name: gcr.io/my-demo-project-20210227/knowledge
  newTag: c3346aae991f27b15bc2cbe212a6fbe150f94475
resources:
- base/deployment.yaml
- base/service.yaml
- base/ingress.yaml
