apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: knowledge-ingress
  labels:
    app: knowledge
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#    - hosts:
#        - empenguin1186.bar.com
#      secretName: tls-secret
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: knowledge-service
              servicePort: 80
            path: /