name: Update tls-secret Workflow
on:
  workflow_dispatch:
env:
  TLS_CERTIFICATE: ${{ secrets.TLS_CERTIFICATE }}
  TLS_SECRET_KEY: ${{ secrets.TLS_SECRET_KEY }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: knowledge-cluster
  GKE_ZONE: asia-northeast1-a
jobs:
  update-tls-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # gcloud CLI のセットアップ
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # GKE 認証情報を取得して、クラスタにデプロイできるようにする
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # tls-secret デプロイ
      - name: update-tls-secret
        run: |-
          TLS_CERTIFICATE=$TLS_CERTIFICATE TLS_SECRET_KEY=$TLS_SECRET_KEY envsubst < ./secrets/tls-secret.tmpl | kubectl apply -f -