name: Update tls-secret Workflow
on:
  workflow_dispatch:
jobs:
  update-tls-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update-tls-secret
        run: |-
          TLS_CERTIFICATE=${{ secrets.TLS_CERTIFICATE }} &&
          TLS_SECRET_KEY=${{ secrets.TLS_SECRET_KEY }} &&
          envsubst < ./secrets/tls-secret.tmpl | kubectl apply -f -