name: Update tls-secret Workflow
on:
  workflow_dispatch:
    inputs:
      tls_certificate:
        description: 'TLS Certificate'
        required: true
        default: 'NONE'
      tls_private_key:
        description: 'TLS Private key'
        required: true
        default: 'NONE'
jobs:
  update-tls-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update-tls-secret
        run: |-
          TLS_CERTIFICATE=${{ github.event.inputs.tls_certificate }} TLS_SECRET_KEY=${{ github.event.inputs.tls_private_key }} envsubst < ./secrets/tls-secret.tmpl