name: Update tls-secret Workflow
on:
  workflow_dispatch:
env:
  TLS_CERTIFICATE: ${{ secrets.TLS_CERTIFICATE }}
  TLS_SECRET_KEY: ${{ secrets.TLS_SECRET_KEY }}
jobs:
  update-tls-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update-tls-secret
        run: |-
          which envsubst
          which kubectl
          echo $TLS_CERTIFICATE
          echo $TLS_SECRET_KEY
          tree .
          TLS_CERTIFICATE=$TLS_CERTIFICATE TLS_SECRET_KEY=$TLS_SECRET_KEY envsubst < ./secrets/tls-secret.tmpl | kubectl apply -f -